spring.application.name=final_project

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://my-project-db.cta0s6cq8r4u.ap-northeast-2.rds.amazonaws.com:3306/myprojectdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=ictfinal

#JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret=1234567890123456789012345678901234567890

tosspayments.secret-key=test_sk_AQ92ymxN34vvbBx9xd0vrajRKXvd

#spring.config.import=application-secret.properties

server.forward-headers-strategy=framework

naver.client-id=d3CrSWAbrzwq0qbeV1J_
naver.redirect-uri=https://www.xyzoffer.xyz/api/social/login/naver/callback
naver.login.uri=https://www.xyzoffer.xyz/social/login/naver
react.uri=https://www.xyzoffer.xyz
kakao.client-id=c80829e0f30e640e7b46302ebf2b0a0e
kakao.login.uri=https://www.xyzoffer.xyz/social/login/kakao
kakao.redirect-uri=https://www.xyzoffer.xyz/api/social/login/kakao/callback

spring.data.redis.host=10.0.3.224
spring.data.redis.port=6379

spring.elasticsearch.uris=http://10.0.3.110:9200

spring.session.store-type=redis
spring.session.redis.flush-mode=on-save

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always