spring.application.name=final_project

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-2.c3uuck8mwgwb.ap-northeast-2.rds.amazonaws.com:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=ictfinal

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=1234567890123456789012345678901234567890

file.upload-dir=C:/upload

tosspayments.secret-key=test_sk_AQ92ymxN34vvbBx9xd0vrajRKXvd
